.3# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [38]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [39]:
print(np.cos(np.pi))
print(np.pi)
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
3.141592653589793
1.1
5.2


In [40]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [41]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,22,6)

print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15 21]


In [42]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
print('')
vec4_reshaped = vec4.reshape(2,5)
print(vec4_reshaped)
print('')
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]

[[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [43]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print('')
print(vec6)
print('')
print(vec5+vec6)
print('')
print(vec5*vec6)
print('')
print(1/vec5)
print('')
print(np.sqrt(vec6))

[1 2 3 4 5]

[3 4 5 6 7]

[ 4  6  8 10 12]

[ 3  8 15 24 35]

[1.         0.5        0.33333333 0.25       0.2       ]

[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [71]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [72]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [73]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [85]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.55758362 0.97541474 0.29950606 0.41692738 0.48442469]
 [0.41698214 0.39562806 0.60610672 0.34716633 0.79173454]
 [0.00520897 0.86662179 0.60083127 0.1309591  0.20601309]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]

[[-0.08225221 -0.3223889   0.70239359 -0.68171242  0.69011925]
 [ 0.60944467 -0.3745554  -0.48426815  0.70241503 -1.40911796]
 [ 0.01045847 -0.21058198 -1.11093635 -0.23088127  0.27468025]
 [ 0.11078805  0.55176782 -1.17179112  0.14516162  0.12144954]
 [-0.00623346 -0.32587094  0.96614096  0.75078466  1.36910696]
 [-1.15630517 -0.03290334 -0.26621145 -0.66905029 -1.20669386]
 [ 0.31109631 -0.45356069 -2.31926619 -0.36826746  0.15112583]
 [-0.09202674  0.81334626  1.81204585  0.43076256 -0.86768194]
 [ 0.59767399 -0.7322376  -1.17095573 -1.12089461  0.76007895]
 [-0.92931307  1.43829347  1.37678545  0.53394509 -0.27838902]]


In [75]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4849557216812939
0.9212023208726394


In [76]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.007274161913238375
2.2737762606831176


In [77]:
# break here for next video!

In [78]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.11470824 -1.06213769  1.4569938  -1.08555452  0.2175733  -0.18859938
  0.08978912  0.84233829 -0.91140556 -0.66755279  0.81706453  1.09919974
 -0.49294515 -0.25035491 -0.21184092 -1.63061629 -1.5638468   0.09959487
  0.30905996]
0.0897891233305385


In [79]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.2175733  -0.18859938  0.08978912  0.84233829 -0.91140556]


In [80]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.11470824 -1.08555452  0.08978912 -0.66755279 -0.49294515]


In [99]:
# what about matrices
print(rand_mat)
print('')
print(rand_mat[1][2])
print('')
print(rand_mat[4][3])
print('')
print(rand_mat[3][2])
print('')
print(rand_mat[1,2])


[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.34716633 0.79173454]
 [0.00520897 0.86662179 0.60083127 0.1309591  0.20601309]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]

3.0

0.19039073398996564

0.9823127487627432

3.0


In [100]:
print(rand_mat[0:2,1:3])

[[3. 3.]
 [3. 3.]]


In [93]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:6] = [1,2,3]
print('')
print(rand_vec)
rand_vec[3:6] = 0
print(rand_vec)

[ 0.11470824 -1.06213769  1.4569938   1.          2.          3.
  0.08978912  0.84233829 -0.91140556 -0.66755279  0.81706453  1.09919974
 -0.49294515 -0.25035491 -0.21184092 -1.63061629 -1.5638468   0.09959487
  0.30905996]

[ 0.11470824 -1.06213769  1.4569938   4.          4.          3.
  0.08978912  0.84233829 -0.91140556 -0.66755279  0.81706453  1.09919974
 -0.49294515 -0.25035491 -0.21184092 -1.63061629 -1.5638468   0.09959487
  0.30905996]

[ 0.11470824 -1.06213769  1.4569938   1.          2.          3.
  0.08978912  0.84233829 -0.91140556 -0.66755279  0.81706453  1.09919974
 -0.49294515 -0.25035491 -0.21184092 -1.63061629 -1.5638468   0.09959487
  0.30905996]
[ 0.11470824 -1.06213769  1.4569938   0.          0.          0.
  0.08978912  0.84233829 -0.91140556 -0.66755279  0.81706453  1.09919974
 -0.49294515 -0.25035491 -0.21184092 -1.63061629 -1.5638468   0.09959487
  0.30905996]


In [101]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.34716633 0.79173454]
 [0.00520897 0.86662179 0.60083127 0.1309591  0.20601309]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.         0.        ]
 [0.00520897 0.86662179 0.60083127 0.         0.        ]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]


In [98]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
print('')
sub_mat[:] = 3
print(sub_mat)


[[3. 3. 3.]
 [3. 3. 3.]]

[[3. 3. 3.]
 [3. 3. 3.]]


In [105]:
print(rand_mat)

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.         0.        ]
 [0.00520897 0.86662179 0.60083127 0.         0.        ]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]


In [107]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print("")
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.         0.        ]
 [0.00520897 0.86662179 0.60083127 0.         0.        ]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]


In [108]:
# break here for next video

In [111]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print('')
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.570723    0.29508444 -0.36904258  1.38973254 -1.52182246 -0.99855081
  0.81005743 -0.26156109  0.10781866  1.43497376  0.22907186 -1.17393285
 -1.52313523 -0.59838988 -0.48212935]

[False  True False  True False False  True False  True  True  True False
 False False False]
[0.29508444 1.38973254 0.81005743 0.10781866 1.43497376 0.22907186]


In [112]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.08225221 -0.3223889   0.70239359 -0.68171242  0.69011925]
 [ 0.60944467 -0.3745554  -0.48426815  0.70241503 -1.40911796]
 [ 0.01045847 -0.21058198 -1.11093635 -0.23088127  0.27468025]
 [ 0.11078805  0.55176782 -1.17179112  0.14516162  0.12144954]
 [-0.00623346 -0.32587094  0.96614096  0.75078466  1.36910696]
 [-1.15630517 -0.03290334 -0.26621145 -0.66905029 -1.20669386]
 [ 0.31109631 -0.45356069 -2.31926619 -0.36826746  0.15112583]
 [-0.09202674  0.81334626  1.81204585  0.43076256 -0.86768194]
 [ 0.59767399 -0.7322376  -1.17095573 -1.12089461  0.76007895]
 [-0.92931307  1.43829347  1.37678545  0.53394509 -0.27838902]]
[0.70239359 0.69011925 0.60944467 0.70241503 0.01045847 0.27468025
 0.11078805 0.55176782 0.14516162 0.12144954 0.96614096 0.75078466
 1.36910696 0.31109631 0.15112583 0.81334626 1.81204585 0.43076256
 0.59767399 0.76007895 1.43829347 1.37678545 0.53394509]


In [113]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.570723    0.29508444 -0.36904258  1.38973254 -1.52182246 -0.99855081
  0.81005743 -0.26156109  0.10781866  1.43497376  0.22907186 -1.17393285
 -1.52313523 -0.59838988 -0.48212935]

[-0.570723    0.29508444 -0.36904258 -5.         -1.52182246 -0.99855081
 -5.         -0.26156109  0.10781866 -5.          0.22907186 -1.17393285
 -1.52313523 -0.59838988 -0.48212935]


In [114]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [117]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [118]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.08225221 -0.3223889   0.70239359 -0.68171242  0.69011925]
 [ 0.60944467 -0.3745554  -0.48426815  0.70241503 -1.40911796]
 [ 0.01045847 -0.21058198 -1.11093635 -0.23088127  0.27468025]
 [ 0.11078805  0.55176782 -1.17179112  0.14516162  0.12144954]
 [-0.00623346 -0.32587094  0.96614096  0.75078466  1.36910696]
 [-1.15630517 -0.03290334 -0.26621145 -0.66905029 -1.20669386]
 [ 0.31109631 -0.45356069 -2.31926619 -0.36826746  0.15112583]
 [-0.09202674  0.81334626  1.81204585  0.43076256 -0.86768194]
 [ 0.59767399 -0.7322376  -1.17095573 -1.12089461  0.76007895]
 [-0.92931307  1.43829347  1.37678545  0.53394509 -0.27838902]]



In [119]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])
print('')
new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.         0.        ]
 [0.00520897 0.86662179 0.60083127 0.         0.        ]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]

[[-0.08225221 -0.3223889   0.70239359 -0.68171242  0.69011925]
 [ 0.60944467 -0.3745554  -0.48426815  0.70241503 -1.40911796]
 [ 0.01045847 -0.21058198 -1.11093635 -0.23088127  0.27468025]
 [ 0.11078805  0.55176782 -1.17179112  0.14516162  0.12144954]
 [-0.00623346 -0.32587094  0.96614096  0.75078466  1.36910696]
 [-1.15630517 -0.03290334 -0.26621145 -0.66905029 -1.20669386]
 [ 0.31109631 -0.45356069 -2.31926619 -0.36826746  0.15112583]
 [-0.09202674  0.81334626  1.81204585  0.43076256 -0.86768194]
 [ 0.59767399 -0.7322376  -1.17095573 -1.12089461  0.76007895]
 [-0.92931307  1.43829347  1.37678545  0.53394509 -0.27838902]]

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.   

In [120]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.         0.        ]
 [0.00520897 0.86662179 0.60083127 0.         0.        ]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]

[[3.         3.         3.         0.41692738 0.48442469]
 [3.         3.         3.         0.         0.        ]
 [0.00520897 0.86662179 0.60083127 0.         0.        ]
 [0.99523426 0.13568653 0.98231275 0.5464639  0.69956647]
 [0.89293673 0.53405506 0.556141   0.19039073 0.9617448 ]]
